# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				skeleton = true
				tropical_fish = true
				bat = true
				item = true
				squid = true
				villager = true
				glow_squid = true
				spider = true
				zombie = true
				cave_spider = true
				creeper = true
				husk = true
				wandering_trader = true
				trader_llama = true
				iron_golem = true
				enderman = true
				witch = true

			[light_sources.settings.entities.friendsandfoes]
				mauler = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.naturalist]
				snail = true
				vulture = true
				firefly = true

			[light_sources.settings.entities.ecologics]
				camel = true
				squirrel = true

			[light_sources.settings.entities.graveyard]
				revenant = true
				skeleton_creeper = true

